Precompute clustering
openproblems-bio/task_batch_integration pull request #18
Opened 2024-12-10 14:23 UTC by rcannood

## Describe your changes

* Add `.obsm["clustering"]` to the solution

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Tests succeed and look good!

2024-12-13 13:22 UTC, mumichae requested changes
Clustering code looks good, with just minor requests. In order for the metrics to recognise the precomputed clusters, I updated the scib version and adjusted the metrics to look for the precomputed clusters, asuming they are stored in `.obs`

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/precompute_clustering_run/script.py
> +except Exception as e:
Nice to see that you implemented rapids_singlecell, however we found that the clustering results are quite different form the CPU implementation and often don't make sense. According to [this thread](https://github.com/scverse/rapids_singlecell/issues/286), this bug could have been fixed recently. But for simplicity, I would go with the igraph implementation, which will be the default in scanpy in the future.

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/precompute_clustering_run/script.py
> +
I would set the CPU algorithm to igraph, as per future warning message from scanpy

```suggestion
kwargs = dict()
if not USE_GPU:
    kwargs |= dict(
        flavor='igraph',
        n_iterations=2,
    )
```

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/precompute_clustering_run/script.py
> +    key_added=key,
```suggestion
    key_added=key,
    **kwargs,
```

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/precompute_clustering_run/script.py
> +input = ad.read_h5ad(par["input"])
You could use the partial reading function to only load `obs` and `obsp`

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/process_dataset/script.py
> +sc.pp.neighbors(adata, use_rep="X_pca", n_neighbors=30, key_added="knn")
definitely good to compute the neighbors as a precomputation step, since it's also used for other metrics. We might want to make `n_neighbors` configurable in the future

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/precompute_clustering_run/script.py
> +key = f'leiden_r{par["resolution"]}'
I would change the resolution pattern to f`leiden_{par["resolution"]}`, since that's what the optimal clustering function is expecting: https://github.com/theislab/scib/blob/d35727305501f905424f19a0e95b61dcda61c460/scib/metrics/clustering.py#L56-L58

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/precompute_clustering_merge/script.py
> +    obs_filt = adata.obs.filter(regex='leiden_r[0-9.]+')
I would adjust the pattern as described in the clustering script

2024-12-13 13:22 UTC, mumichae commented on src/workflows/process_datasets/config.vsh.yaml
> +        default: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
These resolutions must be kept consistent between precomputation and the metrics function. The default range from scib is

```
[0.1, 0.2, ..., 1.8, 1.9, 2.0]
```

2024-12-13 13:22 UTC, mumichae commented on src/data_processors/precompute_clustering_merge/script.py
> +input.obsm["clustering"] = merged
I assume you don't store the the clusters under `.obs`. However, the metric will look in obs for those clusters, so I'd recommend to store them there

2024-12-20 13:55 UTC, mumichae commented on src/data_processors/precompute_clustering_merge/script.py
> +input.obsm["clustering"] = merged
I adjusted the code in the metrics scripts to get the cluster assignments from obsm

2024-12-20 14:01 UTC, mumichae commented
I addressed most of my comments. The only thing that is missing are tests for the clustering component and for checking that the metrics actually use the precomputed values

2025-01-07 14:01 UTC, lazappi commented
Hi @mumichae. Thanks for you help with this! We would like to try and merge it this week. I can help with the code but I wanted to make sure I understood everything first. At the moment the clustering is being pre-computed on the raw, unintegrated data. Is this correct or should we be doing it on the embedding output?

2025-01-09 10:59 UTC, mumichae commented
Hi @lazappi , thanks for catching that detail, I didn't notice it when I was going through the code. The clustering should of course be done for each integration, i.e. after the transformation step, when the kNN graph has been computed.

2025-01-09 12:22 UTC, lazappi commented
Thanks! I thought that would be the cases so I've made some changes already. Should be able to push them soon.

2025-01-09 13:57 UTC, lazappi commented
@rcannood @mumichae I think this should be ready now (for review at least). The CI is failing because I haven't synced the new test resources yet (didn't want to do that without checking in case it messed up something else).

2025-01-10 11:50 UTC, rcannood commented on README.md
> +     obsm: 'X_pca', 'clustering'
Could you run the script to update the readme?

2025-01-10 11:55 UTC, merged