Add SCimilarity
openproblems-bio/task_batch_integration pull request #2
Opened 2024-10-02 09:37 UTC by lazappi

## Describe your changes

Add SCimilarity as a method. Requires adding a new test dataset as SCimilarity can only be run on human data.

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [x] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Tests succeed and look good!

2024-10-02 09:39 UTC, lazappi commented
@rcannood I am relatively confident the component works but we need to work out how to handle the model input. At the moment the component tests fail because there is no example file and they model is not downloaded anywhere.

2024-10-08 11:12 UTC, rcannood requested changes
minor comments

2024-10-08 11:12 UTC, rcannood commented on src/workflows/run_benchmark/main.nf
> +  scimilarity,
You can add a value for model here

```suggestion
  scimilarity.run(
    args: [model: file("https://path/to/model")]
  ),

2024-10-08 11:12 UTC, rcannood commented on scripts/create_resources/test_resources.sh
>  cat > $DATASET_DIR/state.yaml << HERE
Could you create two separate state files, e.g. `$DATASET_DIR/cxg_immune_cell_atlas/state.yaml`? This was an oversight on my part

2024-10-08 11:19 UTC, rcannood reviewed
this could be used to not let the CI run the scimilarity unit test for now:

`src/api/base_method.yaml`:

```yaml
namespace: methods
info:
  type: method
  type_info:
    label: Method
    summary: A method for the batch integration task.
    description: |
      A batch integration method which integrates multiple datasets.
arguments:
  - name: --input
    __merge__: file_dataset.yaml
    direction: input
    required: true
  - name: --output
    __merge__: file_integrated.yaml
    direction: output
    required: true
test_resources:
  - type: python_script
    path: /common/component_tests/check_config.py
```

`src/api/comp_method.yaml`:

```yaml
__merge__: base_method.yaml
test_resources:
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
  - path: /resources_test/task_batch_integration/cxg_mouse_pancreas_atlas
    dest: resources_test/task_batch_integration/cxg_mouse_pancreas_atlas
```

2024-10-08 13:30 UTC, lazappi commented on src/workflows/run_benchmark/main.nf
> +  scimilarity,
This doesn't quite work, you get `ERROR ~ No such variable: scimilarity` from Nextflow (I guess because it's not defined yet)

2024-10-11 12:29 UTC, lazappi commented
Replaced by #3

2024-10-11 12:29 UTC, closed without merging