Add arguments for filtering methods in benchmark workflow
openproblems-bio/task_batch_integration pull request #4
Opened 2024-10-16 15:05 UTC by lazappi

## Describe your changes

Add arguments to the benchmark workflow that methods to be either included or excluded

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [x] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Tests succeed and look good!

2024-10-16 15:15 UTC, rcannood requested changes
minor suggestions

2024-10-16 15:15 UTC, rcannood commented on src/workflows/run_benchmark/main.nf
> +  allowed = true
Need to add a `def` here, or otherwise `allowed` is a global variable, which results in data leakage.

```suggestion
  def allowed = true
```

2024-10-16 15:15 UTC, rcannood commented on src/workflows/run_benchmark/main.nf
> +  return allowed
Alternatively, you could also write:

```suggestion
  if (include) {
    return include.contains(method)
  }
  if (exclude) {
    return !exclude.contains(method)
  }
  return true
```

2024-10-16 15:15 UTC, rcannood commented on src/workflows/run_benchmark/config.vsh.yaml
>      arguments:
Can add a description to the argument group.

```suggestion
  - name: Method filtering
    description: Use these arguments to filter methods by name. By default, all methods are run. If `--methods_include` is defined, only those methods are run. If `--methods_exclude` is defined, all methods except those specified are run. These arguments are mutually exclusive, so don't provide both `--methods_include` and `--methods_exclude`.
    arguments:

2024-10-16 15:15 UTC, rcannood commented on src/workflows/run_benchmark/config.vsh.yaml
> +          '--methods_exclude'.
I think the argument mentioned in the description is wrong. Also, we can simplify it a little bit if the argument group has documentation.

```suggestion
          A list of method ids to include. If specified, only these methods will be run.

2024-10-16 15:15 UTC, rcannood commented on src/workflows/run_benchmark/config.vsh.yaml
> +          '--methods-include'.
I think the argument mentioned in the description is wrong. Also, we can simplify it a little bit if the argument group has documentation.

```suggestion
          A list of method ids to exclude. If specified, all methods except the ones listed will be run.

2024-10-17 06:57 UTC, lazappi commented on src/workflows/run_benchmark/main.nf
> +  allowed = true
Good point. I think your other suggestion is neater though and avoids this.

2024-10-22 13:29 UTC, rcannood approved these changes
LGTM!

2024-10-22 13:29 UTC, merged